import { Injectable } from '@nestjs/common';
import { Prisma } from './generated/client';
import { z } from 'zod';
import { Actor, fail, id, label, parse, requireRole } from './common';
import { PrismaService } from './prisma.service';
import { StockService } from './stock.service';

const money = z.string().regex(/^\d+(?:\.\d{1,2})?$/);
const positiveMoney = money.refine(v => new Prisma.Decimal(v).gt(0));
const page = z.object({ page: z.coerce.number().int().min(1).default(1), page_size: z.coerce.number().int().min(1).max(100).default(20) });
const linesSchema = z.array(z.object({ product_id: id, quantity: z.number().int().positive(), unit_price: positiveMoney.optional() })).min(1).max(100).refine(items => new Set(items.map(x => x.product_id)).size === items.length, '同一产品请合并为一行');
const orderSchema = z.object({ number: label(60), supplier_id: id, lines: linesSchema, note: z.string().max(2000).optional() });
const contractSchema = z.object({ number: label(60), customer_id: id, opportunity_id: id.optional(), lines: linesSchema, note: z.string().max(2000).optional() });

@Injectable()
export class ErpService {
  constructor(private db: PrismaService, private stock: StockService) {}
  private audit(tx: Prisma.TransactionClient, actor: Actor, action: string, type: string, resourceId: string, detail: Record<string, unknown> = {}) { return tx.auditLog.create({ data: { tenantId: actor.tenantId, actorId: actor.id, action, resourceType: type, resourceId, detail: detail as Prisma.InputJsonObject } }); }
  private take(q: { page?: number; page_size?: number }) { return { skip: ((q.page ?? 1) - 1) * (q.page_size ?? 20), take: q.page_size ?? 20 }; }
  private async customer(actor: Actor, customerId: string) {
    requireRole(actor, 'admin', 'sales', 'finance');
    const customer = await this.db.customer.findFirst({ where: { id: customerId, tenantId: actor.tenantId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) } });
    if (!customer) fail('NOT_FOUND', '客户不存在或无权查看', 404);
    return customer;
  }
  private async supplier(actor: Actor, supplierId: string) {
    requireRole(actor, 'admin', 'purchasing', 'warehouse', 'finance');
    const supplier = await this.db.supplier.findFirst({ where: { id: supplierId, tenantId: actor.tenantId } });
    if (!supplier) fail('NOT_FOUND', '供应商不存在', 404);
    return supplier;
  }
  private async purchase(actor: Actor, orderId: string) {
    requireRole(actor, 'admin', 'purchasing', 'warehouse', 'finance');
    const order = await this.db.purchaseOrder.findFirst({ where: { id: orderId, tenantId: actor.tenantId }, include: { supplier: { select: { id: true, name: true } }, lines: true, payable: { include: { payments: { orderBy: { createdAt: 'desc' } } } } } });
    if (!order) fail('NOT_FOUND', '采购单不存在', 404);
    const stockDocuments = await this.db.stockDocument.findMany({ where: { tenantId: actor.tenantId, kind: 'receipt', sourceId: orderId }, include: { movements: { include: { product: { select: { sku: true, name: true } } } } }, orderBy: { createdAt: 'desc' } });
    return { ...order, stockDocuments };
  }
  private async contract(actor: Actor, contractId: string) {
    requireRole(actor, 'admin', 'sales', 'warehouse', 'finance');
    const contract = await this.db.salesContract.findFirst({ where: { id: contractId, tenantId: actor.tenantId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) }, include: { customer: { select: { id: true, name: true } }, lines: true, receivable: { include: { payments: { orderBy: { createdAt: 'desc' } } } } } });
    if (!contract) fail('NOT_FOUND', '销售合同不存在或无权查看', 404);
    const stockDocuments = await this.db.stockDocument.findMany({ where: { tenantId: actor.tenantId, kind: 'shipment', sourceId: contractId }, include: { movements: { include: { product: { select: { sku: true, name: true } } } } }, orderBy: { createdAt: 'desc' } });
    return { ...contract, stockDocuments };
  }
  private async snapshotLines(actor: Actor, lines: z.infer<typeof linesSchema>, priceType: 'purchase' | 'sale') {
    const products = await this.db.product.findMany({ where: { tenantId: actor.tenantId, id: { in: lines.map(x => x.product_id) }, active: true } });
    if (products.length !== lines.length) fail('PRODUCT_INVALID', '产品不存在或已停用');
    const snapshots = lines.map(line => {
      const product = products.find(p => p.id === line.product_id)!;
      const unitPrice = line.unit_price ? new Prisma.Decimal(line.unit_price) : priceType === 'purchase' ? product.purchasePrice : product.salePrice;
      return { productId: product.id, sku: product.sku, name: product.name, quantity: line.quantity, unitPrice, lineTotal: unitPrice.mul(line.quantity) };
    });
    const total = snapshots.reduce((sum, line) => sum.plus(line.lineTotal), new Prisma.Decimal(0));
    if (!total.gt(0)) fail('AMOUNT_INVALID', '单据金额必须大于零');
    return { snapshots, total };
  }
  async listCustomers(actor: Actor, query: Record<string, unknown>) { requireRole(actor, 'admin', 'sales', 'finance'); const q = parse(page.extend({ q: z.string().max(100).optional() }), query); const where: Prisma.CustomerWhereInput = { tenantId: actor.tenantId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}), ...(q.q ? { name: { contains: q.q, mode: 'insensitive' } } : {}) }; const [items,total] = await this.db.$transaction([this.db.customer.findMany({ where, orderBy: { createdAt: 'desc' }, ...this.take(q) }), this.db.customer.count({ where })]); return { items,total,page:q.page,page_size:q.page_size }; }
  async createCustomer(actor: Actor, body: unknown) { requireRole(actor, 'admin', 'sales'); const input = parse(z.object({ code: label(60), name: label(), contact_name: z.string().max(100).optional(), phone: z.string().max(50).optional(), industry: z.string().max(100).optional() }), body); return this.db.$transaction(async tx => { const item = await tx.customer.create({ data: { tenantId: actor.tenantId, code: input.code, name: input.name, contactName: input.contact_name, phone: input.phone, industry: input.industry, ownerId: actor.id } }); await this.audit(tx, actor, 'customer.created', 'customer', item.id); return item; }); }
  async getCustomer(actor: Actor, customerId: string) { const item = await this.customer(actor, customerId); const [opportunities, contracts] = await Promise.all([this.db.opportunity.findMany({ where: { tenantId: actor.tenantId, customerId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) }, orderBy: { createdAt: 'desc' } }), this.db.salesContract.findMany({ where: { tenantId: actor.tenantId, customerId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) }, orderBy: { createdAt: 'desc' } })]); return { ...item, opportunities, contracts }; }
  async listOpportunities(actor: Actor) { requireRole(actor, 'admin', 'sales', 'finance'); return this.db.opportunity.findMany({ where: { tenantId: actor.tenantId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) }, include: { customer: { select: { id: true, name: true } } }, orderBy: { createdAt: 'desc' } }); }
  async createOpportunity(actor: Actor, body: unknown) { requireRole(actor, 'admin', 'sales'); const input = parse(z.object({ customer_id: id, name: label(), estimated_amount: money }), body); await this.customer(actor, input.customer_id); return this.db.$transaction(async tx => { const item = await tx.opportunity.create({ data: { tenantId: actor.tenantId, customerId: input.customer_id, name: input.name, estimatedAmount: new Prisma.Decimal(input.estimated_amount), ownerId: actor.id } }); await this.audit(tx, actor, 'opportunity.created', 'opportunity', item.id); return item; }); }
  async changeOpportunity(actor: Actor, oppId: string, body: unknown) { requireRole(actor, 'admin', 'sales'); const input = parse(z.object({ stage: z.enum(['discovery','proposal','won','lost']) }), body); const opp = await this.db.opportunity.findFirst({ where: { id: oppId, tenantId: actor.tenantId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) } }); if (!opp) fail('NOT_FOUND', '商机不存在或无权操作', 404); if (['won','lost'].includes(opp.stage)) fail('OPPORTUNITY_CLOSED', '商机已结束', 409); return this.db.$transaction(async tx => { const updated = await tx.opportunity.update({ where: { id: oppId }, data: { stage: input.stage } }); await this.audit(tx, actor, 'opportunity.stage_changed', 'opportunity', oppId, { from: opp.stage, to: input.stage }); return updated; }); }
  async listProducts(actor: Actor) { return this.db.product.findMany({ where: { tenantId: actor.tenantId }, include: { balance: true }, orderBy: { createdAt: 'desc' } }); }
  async createProduct(actor: Actor, body: unknown) { requireRole(actor, 'admin', 'purchasing'); const input = parse(z.object({ sku: label(80), name: label(), category: z.string().max(100).optional(), sale_price: money, purchase_price: money, reorder_point: z.number().int().min(0).default(0) }), body); return this.db.$transaction(async tx => { const item = await tx.product.create({ data: { tenantId: actor.tenantId, sku: input.sku, name: input.name, category: input.category, salePrice: new Prisma.Decimal(input.sale_price), purchasePrice: new Prisma.Decimal(input.purchase_price), reorderPoint: input.reorder_point ?? 0, balance: { create: { tenantId: actor.tenantId, quantity: 0 } } } }); await this.audit(tx, actor, 'product.created', 'product', item.id); return item; }); }
  async listSuppliers(actor: Actor) { requireRole(actor, 'admin', 'purchasing', 'warehouse', 'finance'); return this.db.supplier.findMany({ where: { tenantId: actor.tenantId }, orderBy: { createdAt: 'desc' } }); }
  async createSupplier(actor: Actor, body: unknown) { requireRole(actor, 'admin', 'purchasing'); const input = parse(z.object({ code: label(60), name: label(), contact_name: z.string().max(100).optional(), phone: z.string().max(50).optional() }), body); return this.db.$transaction(async tx => { const item = await tx.supplier.create({ data: { tenantId: actor.tenantId, code: input.code, name: input.name, contactName: input.contact_name, phone: input.phone } }); await this.audit(tx, actor, 'supplier.created', 'supplier', item.id); return item; }); }
  async listPurchases(actor: Actor, query: Record<string, unknown>) { requireRole(actor, 'admin', 'purchasing', 'warehouse', 'finance'); const q = parse(page, query); const where = { tenantId: actor.tenantId }; const [items,total] = await this.db.$transaction([this.db.purchaseOrder.findMany({ where, ...this.take(q), orderBy: { createdAt: 'desc' }, include: { supplier: { select: { name: true } } } }), this.db.purchaseOrder.count({ where })]); return { items,total,page:q.page,page_size:q.page_size }; }
  async createPurchase(actor: Actor, body: unknown) { requireRole(actor, 'admin', 'purchasing'); const input = parse(orderSchema, body); const supplier = await this.supplier(actor, input.supplier_id); if (!supplier.active) fail('SUPPLIER_INACTIVE', '供应商已停用'); const { snapshots,total } = await this.snapshotLines(actor, input.lines, 'purchase'); return this.db.$transaction(async tx => { const item = await tx.purchaseOrder.create({ data: { tenantId: actor.tenantId, number: input.number, supplierId: supplier.id, total, note: input.note, createdBy: actor.id, lines: { create: snapshots } }, include: { lines: true } }); await this.audit(tx, actor, 'purchase.created', 'purchase', item.id, { total: total.toFixed(2) }); return item; }); }
  getPurchase(actor: Actor, orderId: string) { return this.purchase(actor, orderId); }
  async confirmPurchase(actor: Actor, orderId: string, body: unknown) { requireRole(actor, 'admin', 'purchasing'); const input = parse(z.object({ version: z.number().int().positive() }), body); const order = await this.purchase(actor, orderId); if (order.status !== 'draft') fail('PURCHASE_STATE', '只能确认草稿采购单', 409); return this.db.$transaction(async tx => { const changed = await tx.purchaseOrder.updateMany({ where: { id: orderId, tenantId: actor.tenantId, version: input.version, status: 'draft' }, data: { status: 'ordered', version: { increment: 1 } } }); if (!changed.count) fail('VERSION_CONFLICT', '单据已更新，请刷新后重试', 409); await this.audit(tx, actor, 'purchase.confirmed', 'purchase', orderId); return tx.purchaseOrder.findUniqueOrThrow({ where: { id: orderId } }); }); }
  receivePurchase(actor: Actor, orderId: string, body: unknown) { return this.stock.receive(actor, orderId, body); }
  async listContracts(actor: Actor, query: Record<string, unknown>) { requireRole(actor, 'admin', 'sales', 'warehouse', 'finance'); const q = parse(page, query); const where = { tenantId: actor.tenantId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) }; const [items,total] = await this.db.$transaction([this.db.salesContract.findMany({ where, ...this.take(q), orderBy: { createdAt: 'desc' }, include: { customer: { select: { name: true } } } }), this.db.salesContract.count({ where })]); return { items,total,page:q.page,page_size:q.page_size }; }
  async createContract(actor: Actor, body: unknown) { requireRole(actor, 'admin', 'sales'); const input = parse(contractSchema, body); const customer = await this.customer(actor, input.customer_id); if (!customer.active) fail('CUSTOMER_INACTIVE', '客户已停用'); if (input.opportunity_id) { const opp = await this.db.opportunity.findFirst({ where: { id: input.opportunity_id, tenantId: actor.tenantId, customerId: customer.id, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) } }); if (!opp) fail('OPPORTUNITY_INVALID', '商机不属于当前客户'); } const { snapshots,total } = await this.snapshotLines(actor, input.lines, 'sale'); return this.db.$transaction(async tx => { const item = await tx.salesContract.create({ data: { tenantId: actor.tenantId, number: input.number, customerId: customer.id, opportunityId: input.opportunity_id, ownerId: actor.id, total, note: input.note, lines: { create: snapshots } }, include: { lines: true } }); await this.audit(tx, actor, 'contract.created', 'contract', item.id, { total: total.toFixed(2) }); return item; }); }
  getContract(actor: Actor, contractId: string) { return this.contract(actor, contractId); }
  async confirmContract(actor: Actor, contractId: string, body: unknown) { requireRole(actor, 'admin', 'sales'); const input = parse(z.object({ version: z.number().int().positive() }), body); const contract = await this.contract(actor, contractId); if (contract.status !== 'draft') fail('CONTRACT_STATE', '只能确认草稿合同', 409); return this.db.$transaction(async tx => { const changed = await tx.salesContract.updateMany({ where: { id: contractId, tenantId: actor.tenantId, version: input.version, status: 'draft' }, data: { status: 'confirmed', version: { increment: 1 } } }); if (!changed.count) fail('VERSION_CONFLICT', '单据已更新，请刷新后重试', 409); await this.audit(tx, actor, 'contract.confirmed', 'contract', contractId); return tx.salesContract.findUniqueOrThrow({ where: { id: contractId } }); }); }
  shipContract(actor: Actor, contractId: string, body: unknown) { return this.stock.ship(actor, contractId, body); }
  stocktake(actor: Actor, body: unknown) { return this.stock.stocktake(actor, body); }
  listStockDocuments(actor: Actor) { return this.db.stockDocument.findMany({ where: { tenantId: actor.tenantId }, include: { movements: { include: { product: { select: { sku: true, name: true } } } } }, orderBy: { createdAt: 'desc' }, take: 100 }); }
  async stockDocumentsPage(actor: Actor, query: Record<string, unknown>) { const q = parse(page.extend({ kind: z.enum(['receipt','shipment','stocktake']).optional() }), query); const where = { tenantId: actor.tenantId, ...(q.kind ? { kind: q.kind } : {}) }; const [items,total] = await this.db.$transaction([this.db.stockDocument.findMany({ where, include: { movements: { include: { product: { select: { sku: true, name: true } } } } }, orderBy: { createdAt: 'desc' }, ...this.take(q) }), this.db.stockDocument.count({ where })]); return { items,total,page:q.page,page_size:q.page_size }; }
  async movementsPage(actor: Actor, query: Record<string, unknown>) { const q = parse(page.extend({ product_id: id.optional() }), query); const where = { tenantId: actor.tenantId, ...(q.product_id ? { productId: q.product_id } : {}) }; const [items,total] = await this.db.$transaction([this.db.stockMovement.findMany({ where, include: { product: { select: { sku: true, name: true } }, document: { select: { number: true, kind: true } } }, orderBy: { createdAt: 'desc' }, ...this.take(q) }), this.db.stockMovement.count({ where })]); return { items,total,page:q.page,page_size:q.page_size }; }
  async inventory(actor: Actor) { return this.db.inventoryBalance.findMany({ where: { tenantId: actor.tenantId }, include: { product: { select: { id: true, sku: true, name: true, unit: true, reorderPoint: true } } }, orderBy: { product: { sku: 'asc' } } }); }
  async movements(actor: Actor, query: Record<string, unknown>) { const q = parse(page.extend({ product_id: id.optional() }), query); return this.db.stockMovement.findMany({ where: { tenantId: actor.tenantId, ...(q.product_id ? { productId: q.product_id } : {}) }, include: { product: { select: { sku: true, name: true } }, document: { select: { number: true, kind: true } } }, orderBy: { createdAt: 'desc' }, ...this.take(q) }); }
  async receivables(actor: Actor) { requireRole(actor, 'admin', 'finance'); return this.db.receivable.findMany({ where: { tenantId: actor.tenantId }, include: { contract: { select: { number: true, customer: { select: { name: true } } } }, payments: { orderBy: { createdAt: 'desc' } } }, orderBy: { createdAt: 'desc' } }); }
  async payables(actor: Actor) { requireRole(actor, 'admin', 'finance'); return this.db.payable.findMany({ where: { tenantId: actor.tenantId }, include: { order: { select: { number: true, supplier: { select: { name: true } } } }, payments: { orderBy: { createdAt: 'desc' } } }, orderBy: { createdAt: 'desc' } }); }
  async recordPayment(actor: Actor, kind: 'receivable' | 'payable', accountId: string, body: unknown) { requireRole(actor, 'admin', 'finance'); const input = parse(z.object({ amount: positiveMoney, reference: label(120) }), body); const amount = new Prisma.Decimal(input.amount); return this.db.$transaction(async tx => { if (kind === 'receivable') { const account = await tx.receivable.findFirst({ where: { id: accountId, tenantId: actor.tenantId } }); if (!account) fail('NOT_FOUND', '应收账款不存在', 404); if (await tx.payment.findFirst({ where: { tenantId: actor.tenantId, receivableId: accountId, reference: input.reference } })) fail('PAYMENT_DUPLICATE', '该应收账款已登记此凭证号', 409); const remaining = account.amount.minus(account.paidAmount); if (amount.gt(remaining)) fail('PAYMENT_EXCEEDS_BALANCE', '收款金额超过未结清余额', 409); const changed = await tx.receivable.updateMany({ where: { id: accountId, tenantId: actor.tenantId, paidAmount: account.paidAmount }, data: { paidAmount: { increment: amount }, status: amount.eq(remaining) ? 'paid' : 'partial' } }); if (!changed.count) fail('VERSION_CONFLICT', '余额已变化，请刷新后重试', 409); const payment = await tx.payment.create({ data: { tenantId: actor.tenantId, receivableId: accountId, amount, reference: input.reference, actorId: actor.id } }); await this.audit(tx, actor, 'receivable.paid', 'receivable', accountId, { amount: input.amount, reference: input.reference }); return payment; } else { const account = await tx.payable.findFirst({ where: { id: accountId, tenantId: actor.tenantId } }); if (!account) fail('NOT_FOUND', '应付账款不存在', 404); if (await tx.payment.findFirst({ where: { tenantId: actor.tenantId, payableId: accountId, reference: input.reference } })) fail('PAYMENT_DUPLICATE', '该应付账款已登记此凭证号', 409); const remaining = account.amount.minus(account.paidAmount); if (amount.gt(remaining)) fail('PAYMENT_EXCEEDS_BALANCE', '付款金额超过未结清余额', 409); const changed = await tx.payable.updateMany({ where: { id: accountId, tenantId: actor.tenantId, paidAmount: account.paidAmount }, data: { paidAmount: { increment: amount }, status: amount.eq(remaining) ? 'paid' : 'partial' } }); if (!changed.count) fail('VERSION_CONFLICT', '余额已变化，请刷新后重试', 409); const payment = await tx.payment.create({ data: { tenantId: actor.tenantId, payableId: accountId, amount, reference: input.reference, actorId: actor.id } }); await this.audit(tx, actor, 'payable.paid', 'payable', accountId, { amount: input.amount, reference: input.reference }); return payment; } }); }
  async dashboard(actor: Actor) { const [customers, activeOpps, orderedPurchases, confirmedContracts, products, receivables, payables] = await Promise.all([this.db.customer.count({ where: { tenantId: actor.tenantId, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) } }), this.db.opportunity.count({ where: { tenantId: actor.tenantId, stage: { notIn: ['won','lost'] }, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) } }), this.db.purchaseOrder.count({ where: { tenantId: actor.tenantId, status: { in: ['ordered','partial_received'] } } }), this.db.salesContract.count({ where: { tenantId: actor.tenantId, status: { in: ['confirmed','partial_shipped'] }, ...(actor.role === 'sales' ? { ownerId: actor.id } : {}) } }), this.db.product.count({ where: { tenantId: actor.tenantId, active: true } }), this.db.receivable.findMany({ where: { tenantId: actor.tenantId, status: { not: 'paid' } }, select: { amount: true, paidAmount: true } }), this.db.payable.findMany({ where: { tenantId: actor.tenantId, status: { not: 'paid' } }, select: { amount: true, paidAmount: true } })]); const sum = (rows: { amount: Prisma.Decimal; paidAmount: Prisma.Decimal }[]) => rows.reduce((n,r) => n.plus(r.amount.minus(r.paidAmount)), new Prisma.Decimal(0)).toFixed(2); return { customers, active_opportunities: activeOpps, purchases_to_receive: orderedPurchases, contracts_to_ship: confirmedContracts, active_products: products, receivable_balance: actor.role === 'finance' || actor.role === 'admin' ? sum(receivables) : null, payable_balance: actor.role === 'finance' || actor.role === 'admin' ? sum(payables) : null, amount_definition: '已实际出库/入库批次金额减已登记收付款，CNY' }; }
  async listUsers(actor: Actor) { requireRole(actor, 'admin'); return this.db.user.findMany({ where: { tenantId: actor.tenantId }, select: { id: true, name: true, email: true, role: true, active: true }, orderBy: { createdAt: 'asc' } }); }
  async createUser(actor: Actor, body: unknown) { requireRole(actor, 'admin'); const input = parse(z.object({ name: label(100), email: z.string().email(), password: z.string().min(12).max(200), role: z.enum(['admin','sales','purchasing','warehouse','finance']) }), body); const { hash } = await import('bcryptjs'); const user = await this.db.user.create({ data: { tenantId: actor.tenantId, name: input.name, email: input.email.toLowerCase(), passwordHash: await hash(input.password,12), role: input.role } }); return { id:user.id, name:user.name, email:user.email, role:user.role }; }
}
